{{- if .Values.loadBalancer.enabled -}}
{{- $fullName := include "mosquitto.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-loadbalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.loadBalancer.ip | quote }}
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: ws
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancer.ip | quote }}

  {{- end }}