{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mosquitto.fullname" . }}-cert
spec:
  secretName: {{ include "mosquitto.fullname" . }}-{{ .Values.certManager.issuerName }}-tls
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: ClusterIssuer
  commonName: {{ include "mosquitto.fullname" . }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
    {{- end }} 
{{ end }}