apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosquitto.fullname" . }}-persist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: 2Gi
